# Visualizing Chipotle's Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter

# set this so the graphs open internally
%matplotlib inline

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [2]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_csv(url, sep='\t')
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

### Step 4. See the first 10 entries

In [ ]:
chipo.head(10)

### Step 5. Create a histogram of the top 5 items bought

In [14]:
item_name = chipo.groupby('item_name').agg({'quantity': 'sum'})
item_name.sort_values(by='quantity', ascending=False)

                                       quantity
item_name
Chicken Bowl                                761
Chicken Burrito                             591
Chips and Guacamole                         506
Steak Burrito                               386
Canned Soft Drink                           351
Chips                                       230
Steak Bowl                                  221
Bottled Water                               211
Chips and Fresh Tomato Salsa                130
Canned Soda                                 126
Chicken Salad Bowl                          123
Chicken Soft Tacos                          120
Side of Chips                               110
Veggie Burrito                               97
Barbacoa Burrito                             91
Veggie Bowl                                  87
Carnitas Bowl                                71
Barbacoa Bowl                                66
Carnitas Burrito                             60
Steak Soft Tacos                             56
6 Pack Soft Drink                            55
Chips and Tomatillo Red Chili Salsa          50
Chicken Crispy Tacos                         50
Chips and Tomatillo Green Chili Salsa        45
Carnitas Soft Tacos                          40
Steak Crispy Tacos                           36
Chips and Tomatillo-Green Chili Salsa        33
Steak Salad Bowl                             31
Nantucket Nectar                             29
Chips and Tomatillo-Red Chili Salsa          25
Barbacoa Soft Tacos                          25
Chips and Roasted Chili Corn Salsa           23
Izze                                         20
Veggie Salad Bowl                            18
Chips and Roasted Chili-Corn Salsa           18
Barbacoa Crispy Tacos                        12
Barbacoa Salad Bowl                          10
Chicken Salad                                 9
Carnitas Crispy Tacos                         8
Veggie Soft Tacos                             8
Burrito                                       6
Veggie Salad                                  6
Carnitas Salad Bowl                           6
Bowl                                          4
Steak Salad                                   4
Salad                                         2
Crispy Tacos                                  2
Chips and Mild Fresh Tomato Salsa             1
Carnitas Salad                                1
Veggie Crispy Tacos                           1

### Step 6. Create a scatterplot with the number of items orderered per order price
#### Hint: Price should be in the X-axis and Items ordered in the Y-axis

### Step 7. BONUS: Create a question and a graph to answer your own question.